//package com.example.meyman.presentation.models
//
//import android.os.Parcelable
//import com.example.meyman.domain.models.RoomAmenitiesModel
//import kotlinx.parcelize.Parcelize
//
//@Parcelize
//data class RoomAmenitiesUI(
//    val accessible_to_disabled_guests: Boolean,
//    val air_conditioner: Boolean,
//    val bath_or_shower: Boolean,
//    val bidet: Boolean,
//    val bottled_water: Boolean,
//    val cable_satellite_tv: Boolean,
//    val city_view: Boolean,
//    val clothes_hanger: Boolean,
//    val coffee_teapot: Boolean,
//    val complimentary_toiletries: Boolean,
//    val connecting_rooms_available: Boolean,
//    val dryer: Boolean,
//    val electric_kettle: Boolean,
//    val flat_screen_tv: Boolean,
//    val folding_bed: Boolean,
//    val fridge: Boolean,
//    val garden_view: Boolean,
//    val hair_dryer: Boolean,
//    val heating: Boolean,
//    val high_toilet: Boolean,
//    val housing: Int,
//    val id: Int,
//    val iron: Boolean,
//    val kitchen_utensils: Boolean,
//    val laptop_safe_box: Boolean,
//    val linen: Boolean,
//    val microwave: Boolean,
//    val minibar: Boolean,
//    val private_bathroom: Boolean,
//    val room_cleaning: Boolean,
//    val room_service: Boolean,
//    val safe: Boolean,
//    val sitting_area: Boolean,
//    val sofa_bed: Boolean,
//    val telephone: Boolean,
//    val toilet_paper: Boolean,
//    val toilet_with_handles: Boolean,
//    val tv: Boolean,
//    val wake_up_service: Boolean,
//    val wardrobe: Boolean,
//    val washing_machine: Boolean,
//    val work_desk: Boolean
//): Parcelable
//
//fun RoomAmenitiesModel.toUI() = RoomAmenitiesUI(
//    accessible_to_disabled_guests,
//    air_conditioner,
//    bath_or_shower,
//    bidet,
//    bottled_water,
//    cable_satellite_tv,
//    city_view,
//    clothes_hanger,
//    coffee_teapot,
//    complimentary_toiletries,
//    connecting_rooms_available,
//    dryer,
//    electric_kettle,
//    flat_screen_tv,
//    folding_bed,
//    fridge,
//    garden_view,
//    hair_dryer,
//    heating,
//    high_toilet,
//    housing,
//    id,
//    iron,
//    kitchen_utensils,
//    laptop_safe_box,
//    linen,
//    microwave,
//    minibar,
//    private_bathroom,
//    room_cleaning,
//    room_service,
//    safe,
//    sitting_area,
//    sofa_bed,
//    telephone,
//    toilet_paper,
//    toilet_with_handles,
//    tv,
//    wake_up_service,
//    wardrobe,
//    washing_machine,
//    work_desk
//)